### ISSUE TITLE
Yaml type provider: Can't read a list of objects

### ISSUE THREAD

**Issue by Kurren123** [fsprojects/FSharp.Configuration#167]
My config.yaml:

```
Targets:
  - Target: 1 0 1 0
    NoSlots: 2
    
  - Target: -1 0 -1 -1
    NoSlots: 2


Tiles:
  - 1 0 0 0
  - 0 0 1 0
  - -1 0 0 0
  - 0 0 -1 -1
```

My code:
```
open FSharp.Configuration
type Config = YamlConfig<"config.yaml">
let config = Config()
printfn "Number of targets: %d" config.Targets.Count
```

Output: `Number of targets: 1`

Operating system: Windows
Target framework: .net 6
Package version: 2.0.0

Any help to be able to parse the list of objects "Targets" would be much appreciated!
