### ISSUE TITLE
Sequence of maps not supported?

### ISSUE THREAD

**Issue by ashic** [fsprojects/FSharp.Configuration#51]
```
Nuget:
    Items:  
        -
          name: Mark McGwire
          hr:   65
          avg:  0.278
        -
          name: Sammy Sosa
          hr:   63
          avg:  0.288
```

Does not seem to work. Seems to be valid yaml. Is there something I'm missing?
