### ISSUE TITLE
[YamlConfig] Allow optional fields in lists

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Configuration#64]
```yaml
Langs:
  - Name: F#
    HKT: false
    Cool: true

  - Name: Rust
    HKT: false

  - Name: Haskell
    HKT: true
    Macros: true
```
would generate:
```fsharp
type Langs_Type() =
  member __.Name: string
  member __.HKT: bool
  member __.Cool: bool option
  member __.Macros: bool option
```
Hint: see how `XmlProvider`/`JsonProvider` from `FSharp.Data` do the same.
