### ISSUE TITLE
[YamlConfig] List properties are initialized with only first element added

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Configuration#66]
* Create a config with a list property which includes several elements
```yaml
AList:
  - Name: foo
    Value: 1
  - Name: bar
    Value: 2
```
* Create an instance of the provided type
```fsharp
let s = Settings() 
// or
let s = MutableSettings()
```
* Result: `s.AList` property contains the first element only.
