### ISSUE TITLE
Yaml merge syntax

### ISSUE THREAD

**Issue by legomind** [fsprojects/FSharp.Configuration#67]
Given the following YAML:

```yaml
Default: &Default
  Db:
    ConnectionString: Data Source=localhost;Initial Catalog=;Integrated Security=True;Application Name=

    
Test: &Test
  Environment: Test
  <<: *Default


ActiveConfig:
  <<: *Test
```

I would think that I should access the desired key like this:

```fsharp
open FSharp.Configuration

type Config = YamlConfig<"Config.yaml">

let config = Config ()

config.ActiveConfig.Environment
```

But, as it turns out, the resulting type is structured like this:

```fsharp
config.ActiveConfig.``<<``.Environment
```

Am I missing something? Obviously using the ``<<`` property is not logical or convenient.
