### ISSUE TITLE
Add support for Nested List

### ISSUE THREAD

**Issue by dotcomputercraft** [fsprojects/FSharp.Configuration#82]
I have the following yaml file:  
```
---
  id: "myApp"
  constraints: 
    - 
      - "attribute"
      - "OPERATOR"
      - "value"
  labels: 
    environment: "staging"
```
and here is the error I get when I use the FSharp.Configuration provider:

"The type provider 'FSharp.Configuration.ConfigTypeProvider + FSharpConfigurationProvider' reported an error: Nested lists are not supported."

Can we add support for Nested list to the FSharp.Configuration provider?  

Please let me know.

John Montoya
